### ISSUE TITLE
how do you install and also is it free or is ever going to be free

### ISSUE THREAD

**Issue by Cxsmo-ai** [DSCHX/DCHX#1]
how do you install and also is it free or is ever going to be free

**Comment by Raz-js** [comment]
You can install using the [release](https://github.com/DSCHX/DCHX/releases/tag/Beta) and I doubt it would be free unless we release the source which I doubt will happen in the near future. As for now its only for windows, but if you use another OS, you could help us out with multiple OS compatibility!

Edit: btw its like $5 Per Month but ig $10 could be lifetime since its early development 🤷‍♂️
